name: flutter_atlanta_packages_example
description: Flutter example app for popular packages
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.1
  go_router: ^10.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
